# Generated by Django 3.2.5 on 2021-08-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20210801_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.option'),
        ),
    ]
