# Generated by Django 3.2.5 on 2021-08-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_query_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='name',
            new_name='description',
        ),
    ]
